@api = http://localhost:8001/api/v1
# ===== get new accessjwt
GET {{api}}/users/new-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpa2FsYWRoaWthcmk1QGdtYWlsLmNvbSIsImlhdCI6MTcxOTI3MTQwMSwiZXhwIjoxNzIxODYzNDAxfQ.wN04YrcyNzFekpfNuNSMwSVcqhblA7yc-a_3cBnmfd4
