@api = http://localhost:8001/api/v1
# ===== get new accessjwt
GET {{api}}/users/new-accessjwt
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpa2FsYWRoaWthcmk1QGdtYWlsLmNvbSIsImlhdCI6MTcxOTI3MTQwMSwiZXhwIjoxNzIxODYzNDAxfQ.wN04YrcyNzFekpfNuNSMwSVcqhblA7yc-a_3cBnmfd4

### ===== Forget Password
POST {{api}}/users/otp
Content-Type: application/json

{
    "email": "biklaladhikari1@gmail.com"
}


### ======= categories
### post new category
POST {{api}}/categories
Content-Type: application/json

{
    "title": "Iphones"
}
### put category
PUT {{api}}/categories/edit
Content-Type: application/json

{
    "_id":"6681fcba29b14d0b58dd2634",
    "title": "Iphones",
    "status":"active"
}